
print("¿cual es tu nombre?")
primer_Nombre = input()
print("¿cual es tu apellido?")
Apellido = input()
print("¿En que trabas o que haces?")
trabajo = input()
print("regalame 2 abjetivos")
primer_abjetivo = input()
segundo_abjetivo = input()
print("¿cual es tus 2 comidas favortias ?")
primera_comida = input()
segunda_comida = input()
print("hola soy "+ primer_Nombre + " " + Apellido +" " + "soy un " + trabajo + " y mis abjetivos son " + primer_abjetivo + " y " + segundo_abjetivo + " y mis comidas favoritas son " + primera_comida + " y " + segunda_comida)
